openapi: "3.0.0"
info:
  title: "sample_back Document"
  version: "0.0.1"
  description: "sample_backのドキュメント"
paths:
  # loginパス
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/requestLogin'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successLogin'
          description: "Successfully"
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failureLogin'
          description: "Client Error"
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failureLogin'
          description: "Internal Server Error"

  # itemパス
  /item:
    get:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successItem'
          description: "Successfully"
        #ユーザー入力ミス
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failureItem'
          description: "Client Error"
        # 在庫切れ
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failureItem'
          description: "Internal Server Error"
  # お店パス
  /shop:
    get:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successShop'
          description: "Successfully"
        #
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failureShop'
          description: "Client Error"
        #
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failureShop'
          description: "Internal Server Error"
  # 在庫数パス
  /stock:
    get:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successStock'
          description: "Successfully"
        #
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failureStock'
          description: "Client Error"
        #
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failureStock'
          description: "Internal Server Error"
  # 一覧取得に成功
  /getItemList:
    get:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getItemList'
          description: "Successfully"
        #ユーザーミス
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failureItemList'
          description: "Client Error"
        #
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failureItemList'
          description: "Internal Server Error"

  # ユーザー登録
  /registUser:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestRegistUser'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successRegistUser'
          description: "Successfully"
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponseInfo'
          description: "Client Error"
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponseInfo'
          description: "Internal Server Error"

components:
  schemas:
    #ユーザー登録のレスポンス（成功）
    successRegistUser:
      allOf:
        - type: object
          properties:
            responseInfo:
              $ref: "#/components/schemas/successResponseInfo"
            data:
              $ref: "#/components/schemas/responseSuccessRegistUser"
      nullable: true
    #APIレスポンス（エラー）
    errorResponse:
      allOf:
        - type: object
          properties:
            responseInfo:
              $ref: "#/components/schemas/errorResponseInfo"
            data:
              $ref: "#/components/schemas/errorData"
    #レスポンスステータスコード（200）
    successResponseInfo:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: 200
        message:
          type: string
          example: successfully
    #レスポンスステータスコード（エラー）
    errorResponseInfo:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: 500
        message:
          type: string
          example: error
    #ログイン時のリクエスト
    requestLogin:
      required:
        - userId
        - password
      type: object
      properties:
        userId:
          type: string
          minLength: 1
          maxLength: 32
          example: sampleUserId1
        password:
          type: string
          format: password
          minLength: 1
          maxLength: 64
          example: samplePassword1
    # ログイン成功
    successLogin:
      required:
        - id
      type: object
      properties:
        userId:
          type: string
          example: sampleUserId1
        userName:
          type: string
          example: sample UserName1
        loginCheck:
          type: boolean
          example: true
    # ログイン失敗
    failureLogin:
      required:
        - id
      type: object
      properties:
        userId:
          type: string
          example:
        userName:
          type: string
          example:
        loginCheck:
          type: boolean
          example: false
        message:
          type: string
          example: "ユーザーIDまたはパスワードが違います。"

    # 商品パス結果：成功
    successItem:
      required:
        - itemId
      type: object
      properties:
        itemId:
          type: string
          example: itemId1
        itemName:
          type: string
          example: ティッシュ（5箱）
        itemPrice:
          type: string
          example: 500
        stock:
          type: string
          example: 100
      xml:
        name: item

    # 商品パス結果：失敗
    failureItem:
      required:
        - itemId
      type: object
      properties:
        itemId:
          type: string
          example:
        itemName:
          type: string
          example:
        itemPrice:
          type: string
          example:
        stock:
          type: string
          example:
      xml:
        name: item

    # お店パス結果：成功
    successShop:
      required:
        - shopId
      type: object
      properties:
        shopId:
          type: string
          example: shopId1
        shopName:
          type: string
          example: 丸スーパー
        shopAddress:
          type: string
          example: 〇県
      xml:
        name: shop

    # お店パス結果：成功
    failureShop:
      required:
        - shopId
      type: object
      properties:
        shopId:
          type: string
          example:
        shopName:
          type: string
          example:
        shopAddress:
          type: string
          example:
      xml:
        name: shop

    # お店パス結果：成功
    successStock:
      required:
        - shopId
        - itemId
      type: object
      properties:
        shopId:
          type: string
          example: shopId1
        itemId:
          type: string
          example: itemId1
        stock:
          type: string
          example: 100
      xml:
        name: shop
    # お店パス結果：成功
    failureStock:
      required:
        - shopId
        - itemId
      type: object
      properties:
        shopId:
          type: string
          example:
        itemId:
          type: string
          example:
        stock:
          type: string
          example:
      xml:
        name: shop

    # 商品一覧取得
    getItemList:
      required:
        - itemId
        - shopId
      type: object
      properties:
        itemId:
          type: string
          example: item001
        itemName:
          type: string
          example: ティッシュ（5箱）
        itemPrice:
          type: string
          example: 500
        shopId:
          type: string
          example: shopId1
        shopName:
          type: string
          example: 丸スーパー
        stock:
          type: string
          example: 100
          xml:
            name: getItemList

      # 商品一覧取得失敗
    failureItemList:
        required:
          - itemId
          - shopId
        type: object
        properties:
          itemId:
            type: string
            example:
          itemName:
            type: string
            example:
          itemPrice:
            type: string
            example:
          shopId:
            type: string
            example:
          shopName:
            type: string
            example:
          stock:
            type: string
            example:
            xml:
              name: failureItemList
    #ユーザー登録時のリクエスト
    requestRegistUser:
      required:
        - userId
        - userName
        - password
      type: object
      properties:
        userId:
          type: string
          minLength: 1
          maxLength: 32
          example: sampleUserId1
        userName:
          type: string
          minLength: 1
          maxLength: 64
          example: sampleUserName1
        password:
          type: string
          format: password
          minLength: 1
          maxLength: 64
          example: samplePassword1
    #ユーザー登録成功
    responseSuccessRegistUser:
      required:
        - userId
        - userName
        - loginCheck
        - message
      type: object
      properties:
        userId:
          type: string
          minLength: 1
          maxLength: 32
          example: sampleUserId1
        userName:
          type: string
          minLength: 1
          maxLength: 64
          example: sampleUserName1
        loginCheck:
          type: boolean
          example: true
        message:
          type: string
          example: ユーザー登録に成功しました。
    #ユーザー登録失敗
    errorData:
      type: object
      properties:
        userId:
          type: string
          minLength: 1
          maxLength: 32
          example:
        userName:
          type: string
          minLength: 1
          maxLength: 64
          example:
        loginCheck:
          type: boolean
          example: false
        message:
          type: string
          example: サンプルエラー。