openapi: "3.0.0"
info:
  title: "sample_back Document"
  version: "0.0.1"
  description: "sample_backのドキュメント"
paths:
  /login:
    post:
      description:
        ログイン時に起動するエンドポイント
      requestBody:
        description: リクエストJSON
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestLogin'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successLogin'
          description: "Successfully"
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failureLogin'
          description: "Client Error"
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failureLogin'
          description: "Internal Server Error"
  /registUser:
    post:
      description: |
        ユーザー登録時に起動するエンドポイント
        
        ユーザー登録に成功時はそのままログインするため、成功時のJSONは/loginと同じ
      requestBody:
        description: リクエストJSON
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registUser'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successLogin'
          description: "Successfully"
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failureLogin'
          description: "Client Error"
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failureLogin'
          description: "Internal Server Error"
components:
  schemas:
    requestLogin:
      required:
        - userId
        - password
      type: object
      properties:
        userId:
          type: string
          example: sampleUserId1
        password:
          type: string
          example: abcdef
    successLogin:
      required:
        - userId
        - userName
        - loginCheck
      type: object
      properties:
        userId:
          type: string
          example: sampleUserId1
        userName:
          type: string
          example: sample UserName1
        loginCheck:
          type: boolean
          example: true
    failureLogin:
      required:
        - userId
        - userName
        - loginCheck
      type: object
      properties:
        userId:
          type: string
          example:
        userName:
          type: string
          example:
        loginCheck:
          type: boolean
          example: false
    registUser:
      required:
        - userId
        - userName
        - password
      type: object
      properties:
        userId:
          type: string
          example: sampleUserId1
        userName:
          type: string
          example: sample UserName1
        password:
          type: string
          example: abcdef